--- # example from Jeff Geerling DevOps book
- name: test ansible-vault with keyring / macOS keychain
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/api_key.yml

  tasks:
    - name: Display the API key from vault
      debug:
        msg: "API Key: {{ myapp_api_key }}"
